services:
  - type: web
    name: amd-hackathon-platform
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
